config/routes.rb
Rails.application.routes.draw do

  get 'gossip/:id_gossip', to: 'gossip#show', as: 'showgossip'
  get 'auteur/:id', to: 'auteur#profil', as:'user_id'
  root to: 'home#index'
  get '/:user/', to: 'home#index'
  get 'team/show', to: 'team#show'
  get 'contact/show', to: 'contact#show'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
resources :gossips
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
belongs_to :user
belongs_to :gossipp
end

app/models/gossipp.rb
class Gossipp < ApplicationRecord
	belongs_to :user
	has_many :joins
	has_many :comments
	has_many :tags, through: :joins
end

app/models/join.rb
class Join < ApplicationRecord
	belongs_to :tag
	belongs_to :gossipp
end

app/models/like.rb
class Like < ApplicationRecord
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
	belongs_to :sender, class_name: "User"
    belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :joins
	has_many :gossipps, through: :joins
end

app/models/user.rb
class User < ApplicationRecord
	belongs_to :city
	has_many :gossipps
	has_many :comments
	has_many :likes


	#MP
	has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
    has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/auteur_controller.rb
class AuteurController < ApplicationController
  def profil
  @auteur = User.find(params[:id])
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def show
  end
end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController
  def show
    @show_gossip = Gossipp.find(params[:id_gossip])
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

  def new
    @gossips = Gossipp.new
  end

  def create
    @user = User.find(58)
    @gossips = Gossipp.new(title:params[:title], content:params[:content], user_id: @user.id)

    if @gossips.save
        redirect_to '/gossips'
    else
    end
  end

  def edit

  @gossips = Gossipp.find(params[:id])
  end

  def update
  @user = User.find(58)
  @gossips = Gossipp.find(params[:id])
  @gossips.update(title: params[:title], content: params[:content])
  redirect_to  gossips_path
  end

  def destroy
    @gossips = Gossipp.find(params[:id])
    @gossips.destroy
    redirect_to gossips_path
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @user = params[:user]
    @gossip = Gossipp.all
  end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  def show
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auteur_helper.rb
module AuteurHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/views/gossip/show.html.erb
<strong>Contenu:</strong> <%= @show_gossip.content %> </br>
<strong>Date de création:</strong> <%= @show_gossip.created_at %> </br>


<input type="button" value="Editer" onclick="document.location.href='<%=edit_gossip_path(@show_gossip.id)%>';" style="background-color: lime">

<a href="<%= gossip_path(@show_gossip.id) %>" class= "btn btn-danger" data-confirm ="êtes vous sur ?" data-method="DELETE"> Supprimer </a>

app/views/gossips/edit.html.erb
<html>
    <head>
        <title>form tag</title>
        <style>
            body {
                text-align:center;
            }
            h1 {
                color:green;
            }
        </style>
    </head>
    <div class="alert alert-success" role="alert">
    </div>
    <body>
        <h1>Créer gossip</h1>

          <%= form_tag url_for(action: 'update'), method: "put" do %>
            Titre Gossip:
            <%= text_field_tag 'title', @gossips.title %>
            <br><br>
            Votre Gossip:
            <%= text_area_tag 'content', @gossips.content %>
            <br><br>
            <%= submit_tag "Valider" %>
        <% end %>
    </body>
    <div class="alert alert-success" role="alert">
    </div>

</html>

app/views/gossips/new.html.erb
<html>
    <head>
        <title>form tag</title>
        <style>
            body {
                text-align:center;
            }
            h1 {
                color:green;
            }
        </style>
    </head>
    <div class="alert alert-success" role="alert">
    </div>
    <body>
        <h1>Créer gossip</h1>

          <%= form_tag url_for(action: 'create'), method: "post" do %>
            Titre Gossip:
            <%= text_field_tag 'title', @gossips.title %>
            <br><br>
            Votre Gossip:
            <%= text_area_tag 'content', @gossips.content %>
            <br><br>
            <%= submit_tag "Créer Gossip" %>
        <% end %>
    </body>
    <div class="alert alert-success" role="alert">
    </div>

</html>