config/routes.rb
Rails.application.routes.draw do

  get 'gossip/:id_gossip', to: 'gossip#show', as: 'showgossip'
  get 'auteur/:id', to: 'auteur#profil', as:'user_id'
  root to: 'home#index'
  get '/:user/', to: 'home#index'
  get 'team/show', to: 'team#show'
  get 'contact/show', to: 'contact#show'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
resources :gossips
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
belongs_to :user
belongs_to :gossipp
end

app/models/gossipp.rb
class Gossipp < ApplicationRecord
	belongs_to :user
	has_many :joins
	has_many :comments
	has_many :tags, through: :joins
end

app/models/join.rb
class Join < ApplicationRecord
	belongs_to :tag
	belongs_to :gossipp
end

app/models/like.rb
class Like < ApplicationRecord
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
	belongs_to :sender, class_name: "User"
    belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :joins
	has_many :gossipps, through: :joins
end

app/models/user.rb
class User < ApplicationRecord
	belongs_to :city
	has_many :gossipps
	has_many :comments
	has_many :likes


	#MP
	has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
    has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
end

app/controllers/auteur_controller.rb
class AuteurController < ApplicationController
  def profil
  @auteur = User.find(params[:id])
  end
end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController
  def show
    @show_gossip = Gossipp.find(params[:id_gossip])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @user = params[:user]
    @gossip = Gossipp.all
  end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  def show
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auteur_helper.rb
module AuteurHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width"/>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <nav class="navbar navbar-expand-lg navbar-light" style ="background-color: lime;">

  <a class="navbar-brand" <%=link_to "GOSSIP PROJECT", root_path%></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

	&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

       <li class="nav-item active">
        <a class="nav-link" <%=link_to "Home 🏠", root_path%><span class="sr-only">(current)</span></a>
      </li>
	&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
      <li class="nav-item active">
        <a class="nav-link" <%=link_to "Team 👨‍👩‍👧‍👦👨‍👩‍👧‍👦", team_show_path%><span class="sr-only">(current)</span></a>
      </li>
	&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
       <li class="nav-item active">
        <a class="nav-link" <%=link_to "Contact 📞", contact_show_path %><span class="sr-only">(current)</span></a>
      </li>
      	&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
      <li class="nav-item active">
       <a class="nav-link" <%=link_to "Créer gossip 📝", new_gossip_path%><span class="sr-only">(current)</span></a>
     </li>

  &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
  &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp

    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>



   </head>
  <body >
    <%= yield %>
  </body>
</html>